- hosts: jitsi
  become: yes
  become_user: root
  become_method: sudo

  vars_prompt:
  - name: 'domain'
    prompt: 'jitsi domain'
    private: no
  - name: 'cert'
    prompt: 'cert?'
    private: no

  roles:
  - role: jitsi
    jitsi:
        cert: '{{ cert }}'
        domain: 'jitsi.{{ domain }}'



