- hosts: onlyoffice
  remote_user: root

  vars_prompt:
  - name: 'domain'
    prompt: 'domain'
    private: no
  - name: 'vhost_port'
    prompt: 'port'
    private: no
  - name: 'admin_email'
    prompt: 'admin email'
    private: no
  - name: 'db_password'
    prompt: 'password for database'
    private: yes
  - name: 'allow_from'
    prompt: 'use onlyoffice from this domain'
    private: no

  roles:
  - role: onlyoffice
    onlyoffice:
        domain: '{{ domain }}'
        allow_from: '{{ allow_from }}'

        db:
            password: '{{ db_password }}'
        http:
            port: '{{ vhost_port }}'
        vhost:
            admin_email: '{{ admin_email }}'

