#
# Install required packages for Debian
#

- name: nginx install
  apt: name={{ item }} state=latest
  with_items:
      - nginx
  when: vhost_modules.http and vhost_.http.server == 'nginx'


- name: certbot install
  apt: name={{ item }} state=latest
  with_items:
      - certbot
  when: vhost_.cert

- name: php install
  apt: name={{ item }} state=latest
  with_items:
      - php
      - php-fpm
  when: vhost_modules.php

- name: php modules install
  apt: name=php-{{ item }} state=latest
  with_items: '{{ vhost_.php.modules }}'
  when: vhost_modules.php and vhost_.php.modules

- name: sql server install
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
      - python-mysqldb
      - php-mysql
      - '{{ vhost_.sql.server }}-server'
  when: false and vhost_modules.sql and vhost_.sql.server in ['mariadb','mysql']


