#
# Nginx post-install setup
#

- include_vars: nginx.yml

# ensure logs dir existence
- name: ensure log dir exists
  block:
  - shell: |
          grep -m1 --color=never "access_log" "{{ server_config }}" |
          sed "s/.*access_log\s\+[\"']\?\(.*\)[\"']\?;/\1/" -
    register: access_log
  - shell: |
          grep -m1 --color=never "error_log" "{{ server_config }}" |
          sed "s/.*error_log\s\+[\"']\?\(.*\)[\"']\?;/\1/" -
    register: error_log
  - file:
      path: '{{ item }}'
      state: directory
      owner: '{{ vhost_dist.http.user }}'
      group: '{{ vhost_dist.http.group }}'
      # TODO: perms
    with_items:
    - '{{ access_log.stdout|dirname }}'
    - '{{ error_log.stdout|dirname }}'


