#
# Nginx setup
#

- include_vars: nginx.yml

- name: nginx directories
  file:
      path: '{{ item }}'
      state: directory
      owner: '{{ vhost_dist.http.user }}'
      group: '{{ vhost_dist.http.group }}'
  with_items:
  - '{{ vhost_dist.http.root }}'
  - /etc/nginx/sites-available
  - /etc/nginx/sites-enabled
  - '{{ vhost_.root }}'

- name: nginx config files
  template:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
      owner: '{{ vhost_dist.http.user }}'
      group: '{{ vhost_dist.http.group }}'
  with_items:
  - src: '{{ vhost_.http.template or "templates/nginx.j2" }}'
    dest: '{{ server_config }}'
  - src: templates/nginx_ssl.j2
    dest: /etc/nginx/conf.d/vhost_ssl.conf

- name: site activation
  when: vhost_.http.enabled|default(false)
  file:
      src: '{{ server_config }}'
      dest: '{{ server_enabled_config }}'
      state: '{% if vhost_.http.enabled %}link{% else %}absent{% endif %}'


