#
# Setup SQL database
#
- name: dabatase
  mysql_db:
    name: '{{ vhost_.domain|replace(".","_") }}'
    config_file: '{{ vhost_.sql.config_file|default("~/.my.cnf") }}'
    collation: '{{ vhost_.sql.collation|default("") }}'
    encoding: '{{ vhost_.sql.encoding|default("") }}'

- name: database user
  mysql_user:
    name: '{{ domain|replace(".","_") }}'
    config_file: '{{ vhost_.sql.config_file|default("~/.my.cnf") }}'
    password: '{{ vhost_.sql.password|default("") }}'
    priv: "{{ domain|replace('.','_') }}.*:ALL,GRANT"

