#
# Default values for optional fields. The values not defined and used in 
# tasks are required
#

# optional modules
server__:
    http:
        server: 'nginx'
        enabled: false
        php: false
        template: ''
        config_extra: ''
    php:
        modules: null
    sql:
        server: 'mariadb'
        password: null
        config_file: null
        collation: null
        encoding: null

    bundle:
        force: false
        remote_src: false
        strip: ''
    git:
        pull: false
        force: false

server_:
    root: '{{ lamp.http.root }}/{{ vhost.domain }}'
    cert: true

    # optional modules
    http: '{{ vhost.http is defined and server__.http }}'
    php:  '{{ vhost.php is defined and server__.php }}'
    sql:  '{{ vhost.sql is defined and server__.sql }}'

    bundle: '{{ vhost.bundle is defined and server__.bundle }}'
    git: '{{ vhost.git is defined and server__.git }}'


