
- block:
  - set_fact: bundle=null
  - set_fact: git=null
  - set_fact: db=null

  - set_fact: bundle='{{ humhub_.bundle|combine(humhub.bundle, recursive=True) }}'
    when: humhub.bundle is defined
  - set_fact: git='{{ humhub_.git|combine(humhub.git, recursive=True) }}'
    when: humhub.git is defined
  - set_fact: db='{{ humhub_.db|combine(humhub.db, recursive=True) }}'
    when: humhub.db is defined


- set_fact:
    http_cfg: '{% include("roles/humhub/templates/nginx.j2") %}'

- name: setup humble site
  include_role:
    name: lamp
  vars:
    vhost:
        domain: '{{ humhub.domain }}'
        admin_email: '{{ humhub.admin_email }}'
        http:
            enabled: true
            config_extra: '{{ http_cfg }}'
        bundle: '{{ bundle }}'
        git: '{{ git }}'
        php:
            modules:
            - curl
            - gd
            - intl
            - ldap
            - zip
        sql: '{{ db }}'


