

- set_fact:
    # need a different varname: see ansible issue #22025
    humhub_: '{{ humhub_|combine(humhub, recursive=True) }}'

- set_fact:
    http_cfg: '{% include("roles/humhub/templates/nginx.j2") %}'

- name: setup humble site
  include_role:
    name: vhost
  vars:
    vhost:
        domain: '{{ humhub.domain }}'
        admin_email: '{{ humhub.admin_email }}'
        http:
            enabled: true
            config_extra: '{{ http_cfg }}'
        bundle: '{{ humhub_.bundle }}'
        git: '{{ humhub_.git }}'
        php:
            modules:
            - curl
            - gd
            - intl
            - ldap
            - zip
        sql: '{{ humhub_.db }}'


