

- set_fact:
    # need a different varname: see ansible issue #22025
    humhub_: '{{ humhub_|combine(humhub, recursive=True) }}'

# generate vhost values
- set_fact:
    humhub_vhost_: '{{ humhub_vhost_|combine(humhub.vhost|default({}), recursive=True) }}'
  vars:
    humhub_vhost_:
        domain: '{{ humhub.domain }}'
        admin_email: '{{ humhub.admin_email }}'
        http:
            enabled: true
            config_extra: '{{ lookup("template", "nginx.j2") }}'
        bundle: '{{ humhub_.bundle }}'
        git: '{{ humhub_.git }}'
        php:
            modules:
            - curl
            - gd
            - intl
            - ldap
            - zip
        sql: '{{ humhub_.db }}'

- debug: var=humhub_vhost_
- meta: end_play

- name: setup humble site
  include_role:
    name: vhost
  vars:
    vhost: '{{ humhub_vhost_ }}'


