humhub__:
    bundle:
        src: 'https://www.humhub.org/en/download/package/humhub-{{ humhub.bundle.version }}.zip'
        remote_src: true
        strip: 'humhub-{{ humhub.bundle.version }}'

    git:
        repo: 'https://github.com/humhub/humhub.git'

    db:
        collation: utf8_unicode_ci
        encoding: utf8

humhub_:
    http:
        enabled: true
        config_extra: '{{ lookup("template", "nginx.j2") }}'

    # optionals
    bundle: '{{ humhub.bundle is defined and humhub__.bundle }}'
    git: '{{ humhub.git is defined and humhub__.git }}'
    db: '{{ humhub.db is defined and humhub__.db }}'



