

- name: platform specific
  block:
  - include_vars:
        file: '{{ ansible_distribution }}.yml'
        name: lamp

- set_fact: server_='{{ server_|combine(server, recursive=True) }}'
- set_fact: lamp_='{{ lamp }}'


- include_tasks: '{{ task.file }}'
  when: task.when
  vars:
    server: '{{ server_ }}'
    lamp: '{{ lamp_ }}'
  loop_control:
      loop_var: task
  with_items:
  # basic setup
  - file: '{{ ansible_distribution }}.yml'
    when: true
  - file: '{{ server_.http.server }}.yml'
    when: '{{ server_.http }}'

  # site files
  - file: bundle.yml
    when: '{{ server_.bundle and server_.bundle.src|default(false) }}'
  - file: git.yml
    when: '{{ server_.git and server_.git.repo|default(false) }}'

  # post install
  - file: '{{ server_.http.server }}_post.yml'
    when: '{{ server_.http }}'
        #- nginx_post.yml
        #- sql.yml


- name: setup mysql
  include_tasks: sql.yml
  when: server.sql is defined and
        server.sql.server in ['mysql', 'mariadb']

- name: restart services
  service: name={{ item }} state=restarted
  with_items:
      - '{% if server.http is defined %}{{ lamp.services[server.http.server] }}{% endif %}'
      - '{% if server.php is defined %}{{ lamp.services.php }}{% endif %}'
      - '{% if server.sql is defined %}{{ lamp.services[server.sql.server] }}{% endif %}'


