#
# Setup SQL database
#
- name: dabatase
  mysql_db:
    name: '{{ server.domain|replace(".","_") }}'
    config_file: '{{ server.sql.config_file|default("~/.my.cnf") }}'
    collation: '{{ server.sql.collation|default("") }}'
    encoding: '{{ server.sql.encoding|default("") }}'

- name: database user
  mysql_user:
    name: '{{ domain|replace(".","_") }}'
    config_file: '{{ server.sql.config_file|default("~/.my.cnf") }}'
    password: '{{ server.sql.password|default("") }}'
    priv: "{{ domain|replace('.','_') }}.*:ALL,GRANT"

