#
# Default values for optional fields. The values not defined and used in 
# tasks are required
#

# optional modules
vhost__:
    http:
        server: 'nginx'
        port: null
        enabled: false
        root: null
        php: false
        template: ''
        config_extra: ''
    php:
        modules: null
    sql:
        server: 'mariadb'
        password: null
        config_file: null
        collation: null
        encoding: null
        migrations: []

    bundle:
        force: false
        remote_src: false
        strip: ''
    git:
        pull: false
        force: false

vhost_:
    cert: true

    # optional modules
    http: '{{ vhost.http is defined and vhost__.http }}'
    php:  '{{ vhost.php is defined and vhost__.php }}'
    sql:  '{{ vhost.sql is defined and vhost__.sql }}'

    bundle: '{{ vhost.bundle is defined and vhost__.bundle }}'
    git: '{{ vhost.git is defined and vhost__.git }}'


